/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_nelson_javanativedemo_Brage */

#ifndef _Included_com_nelson_javanativedemo_Brage
#define _Included_com_nelson_javanativedemo_Brage
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_nelson_javanativedemo_Brage
 * Method:    doInNative
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_nelson_javanativedemo_Brage_doInNative
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
